name: CI/CD

on:
  push:
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Package
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ${{github.workspace}}/dist
        run: |
          tar zcf ../${{github.event.repository.name}}.tar.gz *

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{github.workspace}}/${{github.event.repository.name}}.tar.gz
          token: ${{secrets.ACTION_RELEASE_TOKEN}}
          generate_release_notes: true
          make_latest: true
