name: CI/CD

on:
  push:
  pull_request:
    branches: ['dev']

jobs:
  build:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          yarn install
          yarn build

      - name: Release (1/3)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/configure-pages@v5

      - name: Release (2/3)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Release (3/3)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/deploy-pages@v4
